### ISSUE TITLE
cant get it working...

### ISSUE THREAD

**Issue by tomasenskede** [lrybak/hassio-owserver#9]
first attempt was to install it via HA owserver (1-Wire) the install was fine... but I couldn't connect to it with the 1-wire integration... 

second attempt was to install the ow server on an prepare pi... clean install and I got it semi-working... I got the folders from my 1iwre-hub but nothing else... the 1wire-integration on my HA-PI couldn't connect to the ow server on the other pi... same as with local owserver installed on the ha pi...

any suggestions on how to get 1wire working on HA?

**Comment by lrybak** [comment]
What issue you have? I don't really understand your problem.

**Comment by tomasenskede** [comment]
This is the log from HA when trying to start up the owserver:

1) device? -u?

this is log:
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] owserver.sh: executing... 
[14:55:24] INFO: Configuring -u device
[cont-init.d] owserver.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:55:24] INFO: Starting owserver...
[14:55:24] INFO: Starting owhttpd...

**Comment by tomasenskede** [comment]
![image](https://user-images.githubusercontent.com/32595351/195097173-e8597926-bbd0-4260-96cc-30ea2c2d8901.png)

**Comment by tomasenskede** [comment]
![image](https://user-images.githubusercontent.com/32595351/195099290-22f269bd-0ab5-4b31-9cf8-69bf3af41765.png)
device?? I have an DS9490r USB attached

**Comment by tomasenskede** [comment]
![image](https://user-images.githubusercontent.com/32595351/195144286-19077712-dffc-4cc4-a147-0f98c50463d0.png)

**Comment by lrybak** [comment]
Please post your addon configuration.

**Comment by lrybak** [comment]
Is your device discoverable by HA? Did you confirn it's working at all?

**Comment by tomasenskede** [comment]
I am running this on HA's image for Raspberry PI... where should I find the config? 

I also did try to install the owserver on a clean install raspberry pi... I have that config file... but I would like to have it running on my HA if possible...

**Comment by tomasenskede** [comment]
> Is your device discoverable by HA? Did you confirm it's working at all?

If you reefer to the DS9440r, its working just fine with my Windows server... all my 1wire devices are available and working just fine.

**Comment by tomasenskede** [comment]
![image](https://user-images.githubusercontent.com/32595351/195179914-2a47ecd7-68eb-4b0e-89dd-c7b676fa351a.png)
If I run it with empty device, I got the dummy device and then it startas up and web i/f works... but I cant not connect to it from the ha integration.

**Comment by olalid** [comment]
I believe that the device @tomasenskede is using is nog configured as a serial port and therefore does not provide a device node under Linux.
Instead you are supposed to provide a different configuration option to owserver: "usb" instead of "device /dev/xxxx".
It will then talk directly to the device on a lower level than a device node.

This seems to be impossible to configure currently with this integration due to that it always adds "device" in front of the device node in the configuration file.
From owserver documentation:
Here is a sample configuration file with all the possible parameters included.
              # Sources
              device = /dev/ttyS0 # serial port: DS9097U DS9097 ECLO or LINK
              device = /dev/i2c-0 # i2c port: DS2482-100 or DS2482-800
              usb #       USB device: DS9490 PuceBaboon
              usb = 2 #   Second DS9490
              usb = all # All DS9490s

As @tomasenskede stated above he has a DS9490r, so the correct configuration option should most likely be just "usb" as shown above.

**Comment by lrybak** [comment]
Good point @olalid I will think about fix for that

**Comment by johnpayne** [comment]
Maybe this is the same question worded differently, but how exactly do I specify a device in the YAML?  In my case I have a DS18B20 connected to the GPIO pins.  I've tried several different values for device, but the log shows the addin  hanging at "[06:32:32] INFO: Starting owhttpd..."

Values i've tried for device: 
- DS18B210
- 28.001667239482
- 28001667239482

Thanks!

![image](https://user-images.githubusercontent.com/3162571/196206642-95929a0d-1ac0-412b-903e-63ef90bee172.png)
![image](https://user-images.githubusercontent.com/3162571/196207169-5b3fc746-de0f-4b53-9bff-6474651439d4.png)
![image](https://user-images.githubusercontent.com/3162571/196207515-fbce8a02-93a7-412a-be93-587fbca5586e.png)
![image](https://user-images.githubusercontent.com/3162571/196207814-e47f302c-2da9-4181-be26-b5d318c64bd7.png)

**Comment by olalid** [comment]
@johnpayne the device you need to supply is the bus master, not the temperature sensor. Since you are using a GPIO it would probably not be a device node, but simply "w1". But as discussed above it is currently not possible to provide that type of option to owserver in this integration. You would also need to load and configure the w1 kernel module: https://pinout.xyz/pinout/1_wire before that could work.
(I assume you are running it on a Raspberry Pi here).

**Comment by johnpayne** [comment]
Yes, running a raspberryPi 3b.   Thanks for the reply.  That makes sense.
Maybe I should run home assistant in a docker container so I have more
control over the 1-wire interface...

Thanks!

**Comment by luftdieb** [comment]
Hi, I'm new in HA and I'm trying to get my DS2940 USB Busmuster ready with my X86 HA installation by using original HA image.
I could already install owserver and also HA Plugin can interact with owserver, if owserver run in FAKE mode.
But my problem is similar as here already discussed.. the configuration is not clear, what should I enter under "device".
By using SSH and run dmesg I can see such output, once I'm connecting USB 1W Adapter:
`usb 1-1: USB disconnect, device number 9
[44393.599790] usb 1-1: new full-speed USB device number 10 using xhci_hcd
[44393.728733] usb 1-1: New USB device found, idVendor=04fa, idProduct=2490, bcdDevice= 0.02
[44393.728739] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[44393.814146] w1_master_driver w1_bus_master1: Attaching one wire slave 28.ef89591f64ff crc 24
[44393.815988] w1_master_driver w1_bus_master1: Family 28 for 28.ef89591f64ff.24 is not registered.
[44393.816079] w1_master_driver w1_bus_master1: Attaching one wire slave 28.978d591f64ff crc 25
[44393.819545] w1_master_driver w1_bus_master1: Family 28 for 28.978d591f64ff.25 is not registered.
[44393.819632] w1_master_driver w1_bus_master1: Attaching one wire slave 01.00001a3a860c crc 64
[44393.822957] w1_master_driver w1_bus_master1: Family 1 for 01.00001a3a860c.64 is not registered.
`
Also path is created like  /sys/bus/w1/devices/ which show 2 devices. But once I'm disconnecting both 1w devices, the instances are still shown. But if I'm using same adapter with same sensors on Windows, busmaster react correctly and show temperature result.

I don't like to use ESP8266 device, because 1w USB adapter I've purchased a few days :-(

Hopefully somebody have an idea :-)
Thanks!

**Comment by luftdieb** [comment]
I've solved the problem by making a complete cut.
Have first installed Proxmox, 
then HA by provided OVA vmdk file
then install in proxmox 2nd vm with tiny ubuntu without GUI and just owfs. Then just use webinterface of this instance inside HA. Works perfekt with higher flexibility without loosing too much system performance

**Comment by johnpayne** [comment]
Thanks! I may try that!

**Comment by lrybak** [comment]
I have implemented support for usb 1w devices.
I also introduced three new repositories (stable, beta and edge aka dev) to allow testing before releasing to stable.

You can read more details here:
https://github.com/lrybak/hassio-owserver/blob/master/CHANGELOG.md

USB device support can be tested with v0.3.1-rc1 on beta repository
@johnpayne, @luftdieb, @olalid 

Please let me know if that works for you
